Changes to README.md
Twins-Diwakar-Sharma/BomberMenAI pull request #2
Opened 2019-02-23 15:33 UTC by utkarsh-rg

I have done some changes in README.md which I think you should merge.

2019-02-23 15:36 UTC, Twins-Divyanshu-Sharma requested changes

2019-02-23 15:36 UTC, Twins-Divyanshu-Sharma commented on README.md
> +This is a game that someone else created.
This is bullshit.Remove this line

2019-02-23 15:39 UTC, Twins-Divyanshu-Sharma approved these changes
Looks goo

2019-02-23 15:43 UTC, Twins-Divyanshu-Sharma commented
There is a conflict please resolve that. Will merge after the conflict is resolved.

2022-05-30 11:27 UTC, merged

2022-05-30 11:28 UTC, Twins-Diwakar-Sharma commented
OK thank you.